export const REQUEST_PLAYER_DATA = 'REQUEST_PLAYER_DATA';
export const RECEIVE_PLAYER_DATA = 'RECEIVE_PLAYER_DATA';
export const PLAYER_DATA_ERROR = 'PLAYER_DATA_ERROR';
export const RESET_PLAYER_DATA = 'RESET_PLAYER_DATA';
export const FETCH_HERO_DATA = 'FETCH_HERO_DATA';
export const RESET_HERO_DATA = 'RESET_HERO_DATA';
